// Generated by gencpp from file demo_yolo/BoundingBoxes.msg
// DO NOT EDIT!


#ifndef DEMO_YOLO_MESSAGE_BOUNDINGBOXES_H
#define DEMO_YOLO_MESSAGE_BOUNDINGBOXES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <demo_yolo/BoundingBox.h>

namespace demo_yolo
{
template <class ContainerAllocator>
struct BoundingBoxes_
{
  typedef BoundingBoxes_<ContainerAllocator> Type;

  BoundingBoxes_()
    : boxes()  {
    }
  BoundingBoxes_(const ContainerAllocator& _alloc)
    : boxes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::demo_yolo::BoundingBox_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::demo_yolo::BoundingBox_<ContainerAllocator> >> _boxes_type;
  _boxes_type boxes;





  typedef boost::shared_ptr< ::demo_yolo::BoundingBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_yolo::BoundingBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBoxes_

typedef ::demo_yolo::BoundingBoxes_<std::allocator<void> > BoundingBoxes;

typedef boost::shared_ptr< ::demo_yolo::BoundingBoxes > BoundingBoxesPtr;
typedef boost::shared_ptr< ::demo_yolo::BoundingBoxes const> BoundingBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_yolo::BoundingBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_yolo::BoundingBoxes_<ContainerAllocator1> & lhs, const ::demo_yolo::BoundingBoxes_<ContainerAllocator2> & rhs)
{
  return lhs.boxes == rhs.boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_yolo::BoundingBoxes_<ContainerAllocator1> & lhs, const ::demo_yolo::BoundingBoxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_yolo::BoundingBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_yolo::BoundingBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_yolo::BoundingBoxes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e2299c14fec203f7a579c987c0ef9fa";
  }

  static const char* value(const ::demo_yolo::BoundingBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e2299c14fec203fULL;
  static const uint64_t static_value2 = 0x7a579c987c0ef9faULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_yolo/BoundingBoxes";
  }

  static const char* value(const ::demo_yolo::BoundingBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BoundingBox[] boxes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: demo_yolo/BoundingBox\n"
"string class_name\n"
"int32 x\n"
"int32 y\n"
"int32 w\n"
"int32 h\n"
"\n"
;
  }

  static const char* value(const ::demo_yolo::BoundingBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_yolo::BoundingBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_yolo::BoundingBoxes_<ContainerAllocator>& v)
  {
    s << indent << "boxes[]" << std::endl;
    for (size_t i = 0; i < v.boxes.size(); ++i)
    {
      s << indent << "  boxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::demo_yolo::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.boxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_YOLO_MESSAGE_BOUNDINGBOXES_H
