// Generated by gencpp from file rct_ahr_msgs/NavToLocation.msg
// DO NOT EDIT!


#ifndef RCT_AHR_MSGS_MESSAGE_NAVTOLOCATION_H
#define RCT_AHR_MSGS_MESSAGE_NAVTOLOCATION_H

#include <ros/service_traits.h>


#include <rct_ahr_msgs/NavToLocationRequest.h>
#include <rct_ahr_msgs/NavToLocationResponse.h>


namespace rct_ahr_msgs
{

struct NavToLocation
{

typedef NavToLocationRequest Request;
typedef NavToLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavToLocation
} // namespace rct_ahr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rct_ahr_msgs::NavToLocation > {
  static const char* value()
  {
    return "3a4956001e76e70331ffcf62ffc6a8d5";
  }

  static const char* value(const ::rct_ahr_msgs::NavToLocation&) { return value(); }
};

template<>
struct DataType< ::rct_ahr_msgs::NavToLocation > {
  static const char* value()
  {
    return "rct_ahr_msgs/NavToLocation";
  }

  static const char* value(const ::rct_ahr_msgs::NavToLocation&) { return value(); }
};


// service_traits::MD5Sum< ::rct_ahr_msgs::NavToLocationRequest> should match
// service_traits::MD5Sum< ::rct_ahr_msgs::NavToLocation >
template<>
struct MD5Sum< ::rct_ahr_msgs::NavToLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_msgs::NavToLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::NavToLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_msgs::NavToLocationRequest> should match
// service_traits::DataType< ::rct_ahr_msgs::NavToLocation >
template<>
struct DataType< ::rct_ahr_msgs::NavToLocationRequest>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_msgs::NavToLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::NavToLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rct_ahr_msgs::NavToLocationResponse> should match
// service_traits::MD5Sum< ::rct_ahr_msgs::NavToLocation >
template<>
struct MD5Sum< ::rct_ahr_msgs::NavToLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_msgs::NavToLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::NavToLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_msgs::NavToLocationResponse> should match
// service_traits::DataType< ::rct_ahr_msgs::NavToLocation >
template<>
struct DataType< ::rct_ahr_msgs::NavToLocationResponse>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_msgs::NavToLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::NavToLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCT_AHR_MSGS_MESSAGE_NAVTOLOCATION_H
