// Generated by gencpp from file rct_ahr_msgs/SaveLocation.msg
// DO NOT EDIT!


#ifndef RCT_AHR_MSGS_MESSAGE_SAVELOCATION_H
#define RCT_AHR_MSGS_MESSAGE_SAVELOCATION_H

#include <ros/service_traits.h>


#include <rct_ahr_msgs/SaveLocationRequest.h>
#include <rct_ahr_msgs/SaveLocationResponse.h>


namespace rct_ahr_msgs
{

struct SaveLocation
{

typedef SaveLocationRequest Request;
typedef SaveLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveLocation
} // namespace rct_ahr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rct_ahr_msgs::SaveLocation > {
  static const char* value()
  {
    return "3a4956001e76e70331ffcf62ffc6a8d5";
  }

  static const char* value(const ::rct_ahr_msgs::SaveLocation&) { return value(); }
};

template<>
struct DataType< ::rct_ahr_msgs::SaveLocation > {
  static const char* value()
  {
    return "rct_ahr_msgs/SaveLocation";
  }

  static const char* value(const ::rct_ahr_msgs::SaveLocation&) { return value(); }
};


// service_traits::MD5Sum< ::rct_ahr_msgs::SaveLocationRequest> should match
// service_traits::MD5Sum< ::rct_ahr_msgs::SaveLocation >
template<>
struct MD5Sum< ::rct_ahr_msgs::SaveLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_msgs::SaveLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::SaveLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_msgs::SaveLocationRequest> should match
// service_traits::DataType< ::rct_ahr_msgs::SaveLocation >
template<>
struct DataType< ::rct_ahr_msgs::SaveLocationRequest>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_msgs::SaveLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::SaveLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rct_ahr_msgs::SaveLocationResponse> should match
// service_traits::MD5Sum< ::rct_ahr_msgs::SaveLocation >
template<>
struct MD5Sum< ::rct_ahr_msgs::SaveLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_msgs::SaveLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::SaveLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_msgs::SaveLocationResponse> should match
// service_traits::DataType< ::rct_ahr_msgs::SaveLocation >
template<>
struct DataType< ::rct_ahr_msgs::SaveLocationResponse>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_msgs::SaveLocation >::value();
  }
  static const char* value(const ::rct_ahr_msgs::SaveLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCT_AHR_MSGS_MESSAGE_SAVELOCATION_H
