// Generated by gencpp from file rct_ahr_arm_controller/GoToArmPoseResponse.msg
// DO NOT EDIT!


#ifndef RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSERESPONSE_H
#define RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rct_ahr_arm_controller
{
template <class ContainerAllocator>
struct GoToArmPoseResponse_
{
  typedef GoToArmPoseResponse_<ContainerAllocator> Type;

  GoToArmPoseResponse_()
    : success(false)  {
    }
  GoToArmPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToArmPoseResponse_

typedef ::rct_ahr_arm_controller::GoToArmPoseResponse_<std::allocator<void> > GoToArmPoseResponse;

typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseResponse > GoToArmPoseResponsePtr;
typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseResponse const> GoToArmPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator1> & lhs, const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator1> & lhs, const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rct_ahr_arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rct_ahr_arm_controller/GoToArmPoseResponse";
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToArmPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rct_ahr_arm_controller::GoToArmPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSERESPONSE_H
