// Generated by gencpp from file rct_ahr_arm_controller/GoToArmPoseRequest.msg
// DO NOT EDIT!


#ifndef RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSEREQUEST_H
#define RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rct_ahr_arm_controller
{
template <class ContainerAllocator>
struct GoToArmPoseRequest_
{
  typedef GoToArmPoseRequest_<ContainerAllocator> Type;

  GoToArmPoseRequest_()
    : pose_name()  {
    }
  GoToArmPoseRequest_(const ContainerAllocator& _alloc)
    : pose_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pose_name_type;
  _pose_name_type pose_name;





  typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToArmPoseRequest_

typedef ::rct_ahr_arm_controller::GoToArmPoseRequest_<std::allocator<void> > GoToArmPoseRequest;

typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseRequest > GoToArmPoseRequestPtr;
typedef boost::shared_ptr< ::rct_ahr_arm_controller::GoToArmPoseRequest const> GoToArmPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator1> & lhs, const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose_name == rhs.pose_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator1> & lhs, const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rct_ahr_arm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6184073e8e665fb2bf0be194fc36541";
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6184073e8e665fbULL;
  static const uint64_t static_value2 = 0x2bf0be194fc36541ULL;
};

template<class ContainerAllocator>
struct DataType< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rct_ahr_arm_controller/GoToArmPoseRequest";
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pose_name\n"
;
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToArmPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rct_ahr_arm_controller::GoToArmPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pose_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSEREQUEST_H
