// Generated by gencpp from file rct_ahr_arm_controller/GoToArmPose.msg
// DO NOT EDIT!


#ifndef RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSE_H
#define RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSE_H

#include <ros/service_traits.h>


#include <rct_ahr_arm_controller/GoToArmPoseRequest.h>
#include <rct_ahr_arm_controller/GoToArmPoseResponse.h>


namespace rct_ahr_arm_controller
{

struct GoToArmPose
{

typedef GoToArmPoseRequest Request;
typedef GoToArmPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToArmPose
} // namespace rct_ahr_arm_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rct_ahr_arm_controller::GoToArmPose > {
  static const char* value()
  {
    return "79d88096a3ed8bf571f433b49f30cb27";
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPose&) { return value(); }
};

template<>
struct DataType< ::rct_ahr_arm_controller::GoToArmPose > {
  static const char* value()
  {
    return "rct_ahr_arm_controller/GoToArmPose";
  }

  static const char* value(const ::rct_ahr_arm_controller::GoToArmPose&) { return value(); }
};


// service_traits::MD5Sum< ::rct_ahr_arm_controller::GoToArmPoseRequest> should match
// service_traits::MD5Sum< ::rct_ahr_arm_controller::GoToArmPose >
template<>
struct MD5Sum< ::rct_ahr_arm_controller::GoToArmPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_arm_controller::GoToArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_arm_controller::GoToArmPoseRequest> should match
// service_traits::DataType< ::rct_ahr_arm_controller::GoToArmPose >
template<>
struct DataType< ::rct_ahr_arm_controller::GoToArmPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_arm_controller::GoToArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rct_ahr_arm_controller::GoToArmPoseResponse> should match
// service_traits::MD5Sum< ::rct_ahr_arm_controller::GoToArmPose >
template<>
struct MD5Sum< ::rct_ahr_arm_controller::GoToArmPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_arm_controller::GoToArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_arm_controller::GoToArmPoseResponse> should match
// service_traits::DataType< ::rct_ahr_arm_controller::GoToArmPose >
template<>
struct DataType< ::rct_ahr_arm_controller::GoToArmPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_arm_controller::GoToArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::GoToArmPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCT_AHR_ARM_CONTROLLER_MESSAGE_GOTOARMPOSE_H
