// Generated by gencpp from file rct_ahr_arm_controller/SaveArmPose.msg
// DO NOT EDIT!


#ifndef RCT_AHR_ARM_CONTROLLER_MESSAGE_SAVEARMPOSE_H
#define RCT_AHR_ARM_CONTROLLER_MESSAGE_SAVEARMPOSE_H

#include <ros/service_traits.h>


#include <rct_ahr_arm_controller/SaveArmPoseRequest.h>
#include <rct_ahr_arm_controller/SaveArmPoseResponse.h>


namespace rct_ahr_arm_controller
{

struct SaveArmPose
{

typedef SaveArmPoseRequest Request;
typedef SaveArmPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveArmPose
} // namespace rct_ahr_arm_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rct_ahr_arm_controller::SaveArmPose > {
  static const char* value()
  {
    return "79d88096a3ed8bf571f433b49f30cb27";
  }

  static const char* value(const ::rct_ahr_arm_controller::SaveArmPose&) { return value(); }
};

template<>
struct DataType< ::rct_ahr_arm_controller::SaveArmPose > {
  static const char* value()
  {
    return "rct_ahr_arm_controller/SaveArmPose";
  }

  static const char* value(const ::rct_ahr_arm_controller::SaveArmPose&) { return value(); }
};


// service_traits::MD5Sum< ::rct_ahr_arm_controller::SaveArmPoseRequest> should match
// service_traits::MD5Sum< ::rct_ahr_arm_controller::SaveArmPose >
template<>
struct MD5Sum< ::rct_ahr_arm_controller::SaveArmPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_arm_controller::SaveArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::SaveArmPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_arm_controller::SaveArmPoseRequest> should match
// service_traits::DataType< ::rct_ahr_arm_controller::SaveArmPose >
template<>
struct DataType< ::rct_ahr_arm_controller::SaveArmPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_arm_controller::SaveArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::SaveArmPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rct_ahr_arm_controller::SaveArmPoseResponse> should match
// service_traits::MD5Sum< ::rct_ahr_arm_controller::SaveArmPose >
template<>
struct MD5Sum< ::rct_ahr_arm_controller::SaveArmPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rct_ahr_arm_controller::SaveArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::SaveArmPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rct_ahr_arm_controller::SaveArmPoseResponse> should match
// service_traits::DataType< ::rct_ahr_arm_controller::SaveArmPose >
template<>
struct DataType< ::rct_ahr_arm_controller::SaveArmPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rct_ahr_arm_controller::SaveArmPose >::value();
  }
  static const char* value(const ::rct_ahr_arm_controller::SaveArmPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCT_AHR_ARM_CONTROLLER_MESSAGE_SAVEARMPOSE_H
